app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required,UserMixin
from datetime import datetime
from . import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpeg')
   
    posts = db.relationship('Post', backref='author', lazy=True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"

    
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(cls):
        posts = Post.query.filter_by().all()
        return posts

    @classmethod
    def get_post(cls, id):
        post = Post.query.filter_by(id=id).first()

        return post

    @classmethod
    def count_posts(cls, uname):
        user = User.query.filter_by(username=uname).first()
        posts = Post.query.filter_by(user_id=user.id).all()

        posts_count = 0
        for post in posts:
            posts_count += 1

        return posts_count

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required,DataRequired,length,Email,EqualTo,email_validator
from flask_wtf.file import FileField,FileAllowed
from flask_login import current_user


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    text = TextAreaField('Leave a comment', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config_options

app = Flask(__name__)
db = SQLAlchemy()
bootstrap = Bootstrap()


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    
    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    # Initializing flask extensions
    
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    
    


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template, request, redirect, url_for, abort,flash
from . import main
from ..models import User, Post
from .. import db
from .forms import UpdateProfile,PostForm
from flask_login import login_required, current_user
import datetime
from ..requests import get_quote


# Views


@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    post = Post.get_posts()
    quote = get_quote()

    title = 'Home - Welcome to Perfect Blog app'



    return render_template('index.html', title=title,posts=post,quote=quote)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,content=form.content.data,author=current_user)
        
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@main.route("/post/<int:post_id>", methods=['GET','POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    
    return render_template('post.html', title=post.title, post=post)


@main.route("/post/<int:id>/update", methods=['GET', 'POST'])
@login_required
def update_post(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@main.route("/post/<int:id>/delete", methods=['POST'])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))

app/templates/about.html
{% extends 'base.html'%}
{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            Welcome to Blog app , we are the best blog app since 2020 .Enjoy yourself and post you blog
        </div>
       
    </div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
    
{% endblock %}

app/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">
    <div class="container">
        <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 text-center" >{{ legend }}</legend>
            <div class="form-group" >
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>
    
</div>
{% endblock content %}

app/templates/fourOwfour.html
{% extends 'base.html' %}
{% block content%}
<div class="container">
    <div class="jumbotron text-center">
        <h2> Whooooop!! The page you are trying to access doesnt exist.</h2>
        <p> Go to Home?</p><a href="/" class="btn btn-success">Home</a>
    </div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% for post in posts %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted }}</small>
        </div>
        <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
{% endblock content %}
  

app/templates/index.html
{% extends 'base.html' %}
{%block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Ranga" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cormorant+Upright" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
{%endblock%}

{% block content %}
<div class="card">
    <div class="card-header text-center">
        Quote
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p class="text-center">{{quote.quote}}</p>
            <footer class="blockquote-footer text-center">{{quote.author}}<cite title="Source Title"></cite></footer>
        </blockquote>
    </div>
</div>

{% for post in posts %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="../static/images/default.jpeg">
    <div class="media-body">
        <div class="article-metadata">
            <p class="article-content">{{ post.author.username }}</p>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" >{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
{% endblock content %}

app/templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">

    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <!--navbar for mobile display.-->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">portfolio
                    Website</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--navabar for normal display. navbar and title/brand-->
            <a class="navbar-brand" href="#service">BLOG APP</a>
        </div>

        <!--navbar inside the navbar for navigation items-->
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">

            <ul class="nav navbar-nav pull-right">
                <li><a href="/" active>Home</a></li>
                <li><a href="/about">About</a></li>
                
                
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.new_post')}}">New Post</a></li>
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<br> <br>
<br><br>
<br><br>
<br><br>


    

app/templates/new_comment.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {%block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">{%endblock%}
<!-- content block -->
{% block content %}
<div class="container">
    {{wtf.quick_form(comment_form)}}
</div>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1"
                    href="{{ url_for('main.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                    data-target="#deleteModal">Delete</button>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('main.delete_post', id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/profile/profile.html
{% extends 'base.html' %}


{% block content %}
<link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>
        <div>
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}